export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAILED  = "USER_SIGNIN_FAILED"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DEATAILS_SUCCESS =  "USER_DEATAILS_SUCCESS"
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED"

export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS"

